@echo off
set EXPO_PUBLIC_SUPABASE_URL=https://avnokifuqpazxcwynjmk.supabase.co
set EXPO_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2bm9raWZ1cXBhenhjd3luam1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU2ODM4OTUsImV4cCI6MjA4MTI1OTg5NX0.JaaZj0yvFXGuxHq-OSn57CTKlP0pUxHfk3swPtfq2eg
node scripts\generate-questions.js %*
